"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import { SidebarProvider } from '@/components/ui/sidebar';
// import { listen } from "@tauri-apps/api/event";
// import { Window } from '@tauri-apps/api/window';
// import { useRouter } from "next/navigation";

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // useEffect(() => {
  //   requestAnimationFrame(async () => {
  //     const win = Window.getCurrent();
  //     if (win.label === 'login') {
  //       await win.show();  // only show login window automatically
  //     }
  //   });
  // }, []);

  // const router = useRouter();

  // useEffect(() => {
  //   // Listen for the event from the login window
  //   const unlisten = listen<{ url: string }>("change-route", (event) => {
  //     router.push(event.payload.url);
  //   });

  //   return () => {
  //     unlisten.then((f) => f());
  //   };
  // }, [router]);


  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "light", geistSans.variable, geistMono.variable, "font-sans", figtree.variable)}
    >
      <body className="min-h-full bg-background flex flex-col">
        <TooltipProvider>
          <SidebarProvider>
            {children}
          </SidebarProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}